name: Auto Close if submitted on Wrong branch

on:
  pull_request:
       types: [opened, synchronize, reopened]
       
jobs:
  auto-close-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Check if the branch is template branch
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PAT}}
          script: |
            const baseBranch = context.payload.pull_request.base.ref;
            echo "Base branch is $baseBranch"
            echo "curBranch=$baseBranch" >> $GITHUB_ENV

            
      - name: Close pull request
        if: ${{env.curBranch == 'template' }}
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: 1
          comment: This is Sidharth bot - Please submit in submission branch instead of template branch
          github-token: ${{secrets.PAT}}
